### ISSUE TITLE
Add tree-sitter-readline

### ISSUE THREAD

**Issue by ribru17** [tree-sitter-grammars/.github#1]
Hello, I was wondering if I could be granted permissions to create public repositories in this org in order to transfer my repo https://github.com/ribru17/tree-sitter-readline/transfer. Thank you

**Comment by lewis6991** [comment]
if you can grant owner role to either me, @amaanq or @clason then we can transfer it for you.

**Comment by ribru17** [comment]
Requested to transfer ownership to @lewis6991 :+1:

**Comment by lewis6991** [comment]
https://github.com/tree-sitter-grammars/tree-sitter-readline/
